sudo: false
dist: trusty

services:
- docker

language: bash

branches:
  only:
  - master

script:
  # Build X86 docker image
  - docker build -f ./x86/Dockerfile -t erikdevries/baseimage .
  # Build ARM docker image
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd

  - docker build -f ./arm/Dockerfile -t erikdevries/rpi-baseimage .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

    docker tag erikdevries/baseimage erikdevries/baseimage:latest
    docker tag erikdevries/baseimage erikdevries/baseimage:$TRAVIS_BUILD_NUMBER
    docker push erikdevries/baseimage

    docker tag erikdevries/rpi-baseimage erikdevries/rpi-baseimage:latest
    docker tag erikdevries/rpi-baseimage erikdevries/rpi-baseimage:$TRAVIS_BUILD_NUMBER
    docker push erikdevries/rpi-baseimage
  fi
