sudo: false
dist: trusty

services:
- docker

language: bash

branches:
  only:
  - master

script:
  - make build

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

    docker tag erikdevries/baseimage erikdevries/baseimage:latest
    docker tag erikdevries/baseimage erikdevries/baseimage:$TRAVIS_BUILD_NUMBER
    docker push erikdevries/baseimage

    docker tag erikdevries/rpi-baseimage erikdevries/rpi-baseimage:latest
    docker tag erikdevries/rpi-baseimage erikdevries/rpi-baseimage:$TRAVIS_BUILD_NUMBER
    docker push erikdevries/rpi-baseimage
  fi
